#!/usr/bin/env python3
"""Reproduce Comet Crash M1 analysis without tracking proprietary game data.

Required:
  --elf        decrypted NPEB00142 v1.00 PPU ELF
  --ps3recomp  checkout pinned to e2815326c58d3530936166982672cb09acdef4f9

Optional:
  --param-sfo  PARAM.SFO for TITLE_ID / APP_VER validation.

Generated metadata goes under analysis/generated by default.
Extracted SPU ELFs go under local/ and are intentionally gitignored.
"""
from __future__ import annotations

import argparse
import collections
import datetime as dt
import hashlib
import json
import pathlib
import shutil
import struct
import subprocess
import sys

TOOL_PIN = "e2815326c58d3530936166982672cb09acdef4f9"
EXPECTED_TITLE_ID = "NPEB00142"
EXPECTED_APP_VER = "01.00"
BASELINE = {
    "ppu_functions_approx": 3409,
    "firmware_imports": 171,
    "import_libraries": 18,
    "cellSpurs_imports": 24,
    "embedded_spu_images": 2,
}


def sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def run(cmd: list[str], cwd: pathlib.Path | None = None) -> None:
    print("+", " ".join(str(x) for x in cmd))
    subprocess.run(cmd, cwd=str(cwd) if cwd else None, check=True)


def read_json(path: pathlib.Path):
    return json.loads(path.read_text(encoding="utf-8"))


def find_one(root: pathlib.Path, pattern: str) -> pathlib.Path:
    hits = sorted(root.glob(pattern))
    if len(hits) != 1:
        raise RuntimeError(f"Expected exactly one {pattern} under {root}, found {len(hits)}")
    return hits[0]


def display_path(path: pathlib.Path) -> str:
    try:
        return str(path.resolve().relative_to(pathlib.Path.cwd().resolve())).replace("\\", "/")
    except ValueError:
        return path.name


def validate_ppu_elf(path: pathlib.Path) -> dict:
    with path.open("rb") as f:
        hdr = f.read(0x40)
    if len(hdr) < 0x40 or hdr[:4] != b"\x7fELF":
        raise SystemExit(f"{path} is not an ELF file")
    elf_class, data = hdr[4], hdr[5]
    machine = struct.unpack_from(">H", hdr, 0x12)[0]
    if elf_class != 2:
        raise SystemExit(f"Expected ELFCLASS64 PPU executable, got class {elf_class}")
    if data != 2:
        raise SystemExit(f"Expected big-endian PS3 ELF, got EI_DATA={data}")
    if machine != 21:
        raise SystemExit(f"Expected EM_PPC64 (21), got e_machine={machine}")
    return {
        "size_bytes": path.stat().st_size,
        "sha256": sha256_file(path),
        "elf_class": elf_class,
        "endianness": "big",
        "e_machine": machine,
    }


def parse_param_sfo(path: pathlib.Path) -> dict:
    b = path.read_bytes()
    if len(b) < 20 or b[:4] != b"\x00PSF":
        raise SystemExit(f"{path} is not a PARAM.SFO/PSF file")
    _version, key_start, data_start, count = struct.unpack_from("<IIII", b, 4)
    out = {}
    for i in range(count):
        off = 20 + i * 16
        key_off, fmt, data_len, _max_len, data_off = struct.unpack_from("<HHIII", b, off)
        ks = key_start + key_off
        ke = b.find(b"\x00", ks)
        if ke < 0:
            raise SystemExit("Malformed PARAM.SFO key table")
        key = b[ks:ke].decode("utf-8", "replace")
        raw = b[data_start + data_off:data_start + data_off + data_len]
        if fmt == 0x0404 and len(raw) >= 4:
            value = struct.unpack_from("<I", raw, 0)[0]
        else:
            value = raw.split(b"\x00", 1)[0].decode("utf-8", "replace")
        out[key] = value
    return out


def git_revision(repo: pathlib.Path) -> tuple[str | None, bool | None]:
    try:
        rev = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        dirty = subprocess.run(
            ["git", "-C", str(repo), "diff", "--quiet"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        ).returncode != 0
        return rev, dirty
    except (OSError, subprocess.CalledProcessError):
        return None, None


def marker_flags(data: bytes) -> dict[str, bool]:
    low = data.lower()
    return {
        "multistream": b"multistream" in low,
        "mp3": b"mp3" in low,
        "audio": b"audio" in low,
        "spurs": b"spurs" in low,
    }


def spu_metadata(path: pathlib.Path) -> dict:
    b = path.read_bytes()
    entry = None
    if len(b) >= 0x1C and b[:4] == b"\x7fELF" and b[5] == 2:
        entry = struct.unpack_from(">I", b, 0x18)[0]
    return {
        "file": path.name,
        "size_bytes": len(b),
        "sha256": hashlib.sha256(b).hexdigest(),
        "entry": entry,
        "marker_flags": marker_flags(b),
    }


def markdown_report(r: dict) -> str:
    lines = [
        "# Comet Crash compatibility report",
        "",
        f"Generated: {r['generated_utc']}",
        f"ps3recomp pin: `{r['tooling']['expected_revision']}`",
        f"Observed revision: `{r['tooling']['observed_revision'] or 'unavailable'}`",
        "",
        "## Source identity",
        "",
        f"- ELF SHA-256: `{r['source']['sha256']}`",
        f"- ELF size: {r['source']['size_bytes']:,} bytes",
    ]
    if r.get("param_sfo"):
        lines += [
            f"- TITLE_ID: `{r['param_sfo'].get('TITLE_ID', 'missing')}`",
            f"- APP_VER: `{r['param_sfo'].get('APP_VER', 'missing')}`",
        ]
    lines += [
        "",
        "## PPU/import inventory",
        "",
        f"- PPU functions: **{r['counts']['ppu_functions']:,}**",
        f"- Firmware imports: **{r['counts']['firmware_imports']:,}**",
        f"- Import libraries: **{r['counts']['import_libraries']:,}**",
        f"- cellSpurs imports: **{r['counts']['cellSpurs_imports']:,}**",
        "",
        "| Library | Imports |",
        "|---|---:|",
    ]
    for lib, n in r["imports_by_library"].items():
        lines.append(f"| {lib} | {n} |")
    lines += ["", "## Embedded SPU images", ""]
    for s in r["spu_images"]:
        flags = ", ".join(k for k, v in s["marker_flags"].items() if v) or "none"
        ent = f"0x{s['entry']:08X}" if isinstance(s["entry"], int) else "unknown"
        lines.append(
            f"- `{s['file']}`: {s['size_bytes']:,} bytes; entry {ent}; "
            f"SHA-256 `{s['sha256']}`; markers: {flags}"
        )
    lines += ["", "## Baseline comparison", ""]
    for k, v in r["baseline_comparison"].items():
        lines.append(f"- {k}: {v}")
    lines += [
        "",
        "## Interpretation",
        "",
        "This report inventories the title; it does not claim a successful native boot. "
        "The next milestone is the PPU lift/build followed by capture of the first actual runtime blocker.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--elf", required=True, type=pathlib.Path)
    ap.add_argument("--ps3recomp", required=True, type=pathlib.Path)
    ap.add_argument("--param-sfo", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("analysis/generated"))
    ap.add_argument("--local", type=pathlib.Path, default=pathlib.Path("local/m1"))
    ap.add_argument("--allow-tool-drift", action="store_true")
    args = ap.parse_args()

    elf = args.elf.resolve()
    sdk = args.ps3recomp.resolve()
    out = args.out.resolve()
    local = args.local.resolve()
    out.mkdir(parents=True, exist_ok=True)
    local.mkdir(parents=True, exist_ok=True)

    source = validate_ppu_elf(elf)
    rev, dirty = git_revision(sdk)
    if rev != TOOL_PIN and not args.allow_tool_drift:
        raise SystemExit(
            f"ps3recomp revision mismatch: expected {TOOL_PIN}, observed {rev}. "
            "Run tools/bootstrap_ps3recomp.ps1 or explicitly pass --allow-tool-drift."
        )

    sfo = parse_param_sfo(args.param_sfo.resolve()) if args.param_sfo else None
    if sfo:
        if sfo.get("TITLE_ID") != EXPECTED_TITLE_ID:
            raise SystemExit(f"Wrong title: expected {EXPECTED_TITLE_ID}, got {sfo.get('TITLE_ID')}")
        app_ver = str(sfo.get("APP_VER", ""))
        if app_ver and app_ver != EXPECTED_APP_VER:
            raise SystemExit(f"Wrong APP_VER: expected {EXPECTED_APP_VER}, got {app_ver}")

    loader_dir = out / "loader"
    if loader_dir.exists():
        shutil.rmtree(loader_dir)
    loader_dir.mkdir(parents=True)

    spu_dir = local / "spu_images"
    if spu_dir.exists():
        shutil.rmtree(spu_dir)
    spu_dir.mkdir(parents=True)

    py = sys.executable
    run([py, str(sdk / "tools" / "ppu_loader.py"), str(elf), "-o", str(loader_dir)], cwd=sdk)
    named_imports = out / "imports_named.json"
    run([py, str(sdk / "tools" / "gen_imports.py"), str(elf), "-o", str(named_imports)], cwd=sdk)
    run([py, str(sdk / "tools" / "extract_spu_images.py"), str(elf), "-o", str(spu_dir)], cwd=sdk)

    functions_path = find_one(loader_dir, "*.functions.json")
    imports_path = find_one(loader_dir, "*.imports.json")
    functions = read_json(functions_path)
    imports = read_json(imports_path)

    libs = collections.Counter(str(x.get("library", "<unknown>")) for x in imports)
    spurs = sum(n for lib, n in libs.items() if lib.lower() == "cellspurs")
    spu = [spu_metadata(p) for p in sorted(spu_dir.glob("*.elf"))]

    counts = {
        "ppu_functions": len(functions),
        "firmware_imports": len(imports),
        "import_libraries": len(libs),
        "cellSpurs_imports": spurs,
        "embedded_spu_images": len(spu),
    }
    comparison = {
        "ppu_functions": (
            f"{counts['ppu_functions']} "
            f"(prior approximate baseline {BASELINE['ppu_functions_approx']}; "
            f"delta {counts['ppu_functions'] - BASELINE['ppu_functions_approx']:+d})"
        ),
        "firmware_imports": (
            f"{counts['firmware_imports']} / expected {BASELINE['firmware_imports']} -> "
            f"{'MATCH' if counts['firmware_imports'] == BASELINE['firmware_imports'] else 'MISMATCH'}"
        ),
        "import_libraries": (
            f"{counts['import_libraries']} / expected {BASELINE['import_libraries']} -> "
            f"{'MATCH' if counts['import_libraries'] == BASELINE['import_libraries'] else 'MISMATCH'}"
        ),
        "cellSpurs_imports": (
            f"{counts['cellSpurs_imports']} / expected {BASELINE['cellSpurs_imports']} -> "
            f"{'MATCH' if counts['cellSpurs_imports'] == BASELINE['cellSpurs_imports'] else 'MISMATCH'}"
        ),
        "embedded_spu_images": (
            f"{counts['embedded_spu_images']} / expected {BASELINE['embedded_spu_images']} -> "
            f"{'MATCH' if counts['embedded_spu_images'] == BASELINE['embedded_spu_images'] else 'MISMATCH'}"
        ),
    }

    report = {
        "schema": 1,
        "generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "target": {"title_id": EXPECTED_TITLE_ID, "version": "v1.00"},
        "source": source,
        "param_sfo": sfo,
        "tooling": {
            "expected_repository": "sp00nznet/ps3recomp",
            "expected_revision": TOOL_PIN,
            "observed_revision": rev,
            "working_tree_dirty": dirty,
        },
        "counts": counts,
        "imports_by_library": dict(sorted(libs.items())),
        "spu_images": spu,
        "baseline_comparison": comparison,
        "artifacts": {
            "functions_json": display_path(functions_path),
            "imports_json": display_path(imports_path),
            "named_imports_json": display_path(named_imports),
            "spu_binaries": "local-only; intentionally gitignored",
        },
    }

    (out / "compatibility.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (out / "compatibility.md").write_text(markdown_report(report), encoding="utf-8")
    print(f"\nWrote {out / 'compatibility.json'}")
    print(f"Wrote {out / 'compatibility.md'}")
    print("Embedded SPU binaries remain local-only:", spu_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
